### ISSUE TITLE
C&P bugs out program

### ISSUE THREAD

**Issue by dpatuwo** [bryanmytko/regex_game#3]
Whenever I copy & pasted a section of regex the game would bug out until i delete the section that i c&p'd

**Comment by bryanmytko** [comment]
@dpatuwo I can't seem to reproduce this. Copy / Pasting seems to work okay for me.
Can you provide a specific example?

**Comment by dpatuwo** [comment]
When I copy and pasted stuff, I didn't copy and paste the whole section of code.  I would take small snippets of code and put them in, and that's how I got the bugs

**Comment by bryanmytko** [comment]
C&P seems to work for me. Actions are triggered on keyup so maybe typing the last character is required if you paste the entire solution, which isn't intended behavior anyway. Need specific steps to reproduce if there are other bugs.
