### ISSUE TITLE
Error on second question

### ISSUE THREAD

**Issue by Mekebrown** [bryanmytko/regex_game#4]
For the "A Lannister always pays their debts. Find the numeric strings!" question, I entered \d.+ and this was marked correct. 

It is not.

I tried it again and that answer was incorrect. I tried a third time and it was correct. _Shrug_

Yes! I get ALL THE ISSUE POINTS! BWAHAHA!

**Comment by bryanmytko** [comment]
@Githubbubber Thanks, I think I got this one sorted out now! The issue was that sometimes the "1" was previously matched and not correctly being removed from the array that collects matches.
